services:
  # Web service
  - type: web
    name: groops
    env: go
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URL
        value: https://groops-api.onrender.com/auth/google/callback
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_NOTIFICATIONS_FROM_EMAIL
        value: notifications@groops.fun
      - key: SENDGRID_FROM_NAME
        value: Groops
      - key: DB_HOST
        fromDatabase:
          name: groops-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: groops-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: groops-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: groops-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: groops-db
          property: database

  # PostgreSQL Database
  - type: pserv
    name: groops-db
    plan: standard 